# Generated by Django 3.1.14 on 2023-08-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20230827_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
