# Generated by Django 3.1.14 on 2023-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20230827_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Название(eng)'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.TextField(null=True, verbose_name='Название(japan)'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_ru',
            field=models.TextField(verbose_name='Название(rus)'),
        ),
    ]
